test: run_functional_tests

run_functional_tests:
	docker run --rm -v $$(pwd):/var/tmp centos:6 /var/tmp/tests/build_rpm.sh
	docker run --rm -v $$(pwd):/var/tmp debian:7 /var/tmp/tests/build_deb.sh
	docker run --rm -v $$(pwd):/var/tmp centos:6 /var/tmp/tests/check.sh
