#!/bin/sh
set -e

if [ "$1" = "configure" ]; then

    if ! getent group mamonsu > /dev/null 2>&1 ; then
        addgroup --system --quiet mamonsu
    fi
    if ! getent passwd mamonsu > /dev/null 2>&1 ; then
        adduser --quiet \
            --system --disabled-login --ingroup mamonsu \
            --home /var/run/mamonsu/ --no-create-home \
            mamonsu
    fi

    mkdir -p /var/run/mamonsu
    chown mamonsu:mamonsu /var/run/mamonsu

    mkdir -p /etc/mamonsu/plugins
    touch /etc/mamonsu/plugins/__init__.py
    [ -f /etc/mamonsu/agent.conf ] || cp /usr/share/mamonsu/example_linux.conf /etc/mamonsu/agent.conf && chown mamonsu:mamonsu /etc/mamonsu/agent.conf

    chown mamonsu:mamonsu /var/log/mamonsu
    chown mamonsu:mamonsu /var/lib/mamonsu

fi

if [ -x "/etc/init.d/mamonsu" ]; then
    update-rc.d mamonsu defaults >/dev/null
fi

exit 0
