#!/bin/sh

set -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|remove)
	:
	;;
    purge)
        rm -rf /etc/mamonsu
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac