#!/bin/sh
set -e

if [ "$1" = "configure" ]; then

    if ! getent group mamonsu > /dev/null 2>&1 ; then
        addgroup --system --quiet mamonsu
    fi
    if ! getent passwd mamonsu > /dev/null 2>&1 ; then
        adduser --quiet \
            --system --disabled-login --ingroup mamonsu \
            --home /var/run/mamonsu/ --no-create-home \
            mamonsu
    fi
	if [ -x /bin/systemd-tmpfiles ]; then
		systemd-tmpfiles --create > /dev/null 2>&1 || :
	else
		mkdir -p /var/run/mamonsu
		chown -R mamonsu:mamonsu /var/run/mamonsu
	fi

    mkdir -p /etc/mamonsu/plugins
    touch /etc/mamonsu/plugins/__init__.py
    [ -f /etc/mamonsu/agent.conf ] || cp /usr/share/mamonsu/example_linux.conf /etc/mamonsu/agent.conf
	mkdir -p /var/log/mamonsu
	mkdir -p /var/lib/mamonsu
    chown mamonsu:mamonsu /var/log/mamonsu
    chown mamonsu:mamonsu /var/lib/mamonsu
    chown -R mamonsu:mamonsu /etc/mamonsu
fi
