#!/bin/sh

set -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
	:
	;;
    remove)
	[ -x /etc/init.d/mamonsu ] && /etc/init.d/mamonsu stop 1>/dev/null 2>/dev/null || true
	[ -x /sbin/chkconfig ] && /sbin/chkconfig mamonsu off 1>/dev/null 2>/dev/null || true
	;;
    purge)
	[ -x /etc/init.d/mamonsu ] && /etc/init.d/mamonsu stop 1>/dev/null 2>/dev/null || true
	[ -x /sbin/chkconfig ] && /sbin/chkconfig mamonsu off 1>/dev/null 2>/dev/null || true
        rm -fr /var/log/mamonsu
        rm -fr /var/run/mamonsu
        rm -fr /var/lib/mamonsu
        rm -f /etc/mamonsu/agent.conf
        rm -rf /etc/mamonsu/plugins
	;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
esac
