#!/bin/sh

set -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
	:
	;;
    remove)
	[ -x /etc/init.d/mamonsu ] && /etc/init.d/mamonsu stop 1>/dev/null 2>/dev/null || true
	[ -x /sbin/chkconfig ] && /sbin/chkconfig mamonsu off 1>/dev/null 2>/dev/null || true
	;;
    purge)
	[ -x /etc/init.d/mamonsu ] && /etc/init.d/mamonsu stop 1>/dev/null 2>/dev/null || true
	[ -x /sbin/chkconfig ] && /sbin/chkconfig mamonsu off 1>/dev/null 2>/dev/null || true
        rm -fr /var/log/mamonsu
        rm -fr /var/run/mamonsu
        rm -fr /var/lib/mamonsu
	;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

case "$1" in
remove)
        type systemctl > /dev/null 2>&1  && rm /etc/init.d/mamonsu || :
        type systemctl > /dev/null 2>&1  && systemctl daemon-reload || :
        ;;
*)
;;
esac

