from datetime import datetime

from mamonsu.plugins.pgsql.archive_command import ArchiveCommand
from mamonsu.plugins.pgsql.bgwriter import BgWriter
from mamonsu.plugins.pgsql.checkpoint import Checkpoint
from mamonsu.plugins.pgsql.connections import Connections
from mamonsu.plugins.pgsql.databases import Databases
from mamonsu.plugins.pgsql.health import PgHealth
from mamonsu.plugins.pgsql.instance import Instance
from mamonsu.plugins.pgsql.oldest import Oldest
from mamonsu.plugins.pgsql.pg_buffercache import PgBufferCache
from mamonsu.plugins.pgsql.pg_locks import PgLocks
from mamonsu.plugins.pgsql.replication import Replication
from mamonsu.plugins.pgsql.wal import Wal
from mamonsu.plugins.system.linux.memory import Memory
from mamonsu.plugins.system.linux.proc_stat import ProcStat


def generate_dashboard(template, uuid):
    dashboard_xml = """
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<zabbix_export>
   <version>6.0</version>
   <date>{0}</date>
   <groups>
      <group>
         <uuid></uuid>
         <name>Templates</name>
      </group>
   </groups>
   <templates>
      <template>
         <uuid>{42}</uuid>
         <template>{1}</template>
         <name>{1}</name>
         <groups>
            <group>
               <name>Templates</name>
            </group>
         </groups>
         <dashboards>
            <dashboard>
               <uuid>{42}</uuid>
               <name>Mamonsu Dashboard</name>
               <pages>
                  <page>
                     <widgets>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <x>4</x>
                           <y>2</y>
                           <width>10</width>
                           <height>6</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{2}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <y>8</y>
                           <width>12</width>
                           <height>5</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{3}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <x>12</x>
                           <y>8</y>
                           <width>12</width>
                           <height>5</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{4}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <x>14</x>
                           <y>2</y>
                           <width>10</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{5}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Archived Files</name>
                           <x>16</x>
                           <y>23</y>
                           <width>4</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{6}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Autovacuum Workers</name>
                           <y>16</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{7}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>bgwriter Buffers</name>
                           <y>19</y>
                           <width>8</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{8}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>bgwriter write/sync</name>
                           <x>8</x>
                           <y>19</y>
                           <width>8</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{9}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Blocks Hit</name>
                           <x>14</x>
                           <y>6</y>
                           <width>2</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{10}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Blocks Read</name>
                           <x>16</x>
                           <y>6</y>
                           <width>2</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{11}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Cache Hit Ratio</name>
                           <y>2</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{12}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Checkpoints Count</name>
                           <x>16</x>
                           <y>19</y>
                           <width>8</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{13}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Checkpoints write/sync</name>
                           <y>23</y>
                           <width>8</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{14}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Checksum Failures</name>
                           <x>4</x>
                           <y>13</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{15}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>TS Committed</name>
                           <x>22</x>
                           <y>6</y>
                           <width>2</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{16}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Current Available RAM</name>
                           <x>12</x>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{17}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Current Cached RAM</name>
                           <x>18</x>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{18}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Current I/O time</name>
                           <x>21</x>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{19}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Current Used RAM</name>
                           <x>15</x>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{20}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Deadlocks</name>
                           <y>13</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{21}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Events</name>
                           <x>8</x>
                           <y>23</y>
                           <width>8</width>
                           <height>4</height>
                           <fields>
                              <field>
                                 <type>GRAPH</type>
                                 <name>graphid</name>
                                 <value>
                                    <name>{22}</name>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Failed Archived Files</name>
                           <x>16</x>
                           <y>25</y>
                           <width>4</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{23}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Files Need to Archive</name>
                           <x>20</x>
                           <y>23</y>
                           <width>4</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{24}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Non-active Replication Slots</name>
                           <y>27</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{25}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Oldest Transaction</name>
                           <x>4</x>
                           <y>16</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{26}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Ping</name>
                           <x>3</x>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{27}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Server version</name>
                           <width>3</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{28}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Replication Lag</name>
                           <x>4</x>
                           <y>27</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{29}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Size of Files Need to Archive</name>
                           <x>20</x>
                           <y>25</y>
                           <width>4</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{30}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Temp Bytes</name>
                           <x>20</x>
                           <y>6</y>
                           <width>2</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{31}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Temp Files</name>
                           <x>18</x>
                           <y>6</y>
                           <width>2</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{32}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Total User Connections</name>
                           <y>5</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{33}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Tuples Deleted</name>
                           <x>16</x>
                           <y>16</y>
                           <width>8</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>source_type</name>
                                 <value>1</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show_legend</name>
                                 <value>0</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{34}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Tuples Fetched</name>
                           <x>8</x>
                           <y>13</y>
                           <width>8</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>source_type</name>
                                 <value>1</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show_legend</name>
                                 <value>0</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{35}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Tuples Inserted</name>
                           <x>8</x>
                           <y>16</y>
                           <width>8</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>source_type</name>
                                 <value>1</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show_legend</name>
                                 <value>0</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{36}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>GRAPH_CLASSIC</type>
                           <name>Tuples Returned</name>
                           <x>16</x>
                           <y>13</y>
                           <width>8</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>source_type</name>
                                 <value>1</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show_legend</name>
                                 <value>0</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{37}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>Uptime</name>
                           <x>6</x>
                           <width>6</width>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{38}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                            <type>GRAPH_CLASSIC</type>
                            <name>WAL Records</name>
                            <x>8</x>
                            <y>27</y>
                            <width>16</width>
                            <height>6</height>
                            <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>source_type</name>
                                 <value>1</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show_legend</name>
                                 <value>0</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{39}</key>
                                    <host>{1}</host>
                                 </value>
                              </field> 
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>WAL Sync Duty</name>
                           <x>4</x>
                           <y>30</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{40}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                        <widget>
                           <type>ITEM</type>
                           <name>WAL Write Speed</name>
                           <y>30</y>
                           <width>4</width>
                           <height>3</height>
                           <fields>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>4</value>
                              </field>
                              <field>
                                 <type>INTEGER</type>
                                 <name>show</name>
                                 <value>2</value>
                              </field>
                              <field>
                                 <type>ITEM</type>
                                 <name>itemid</name>
                                 <value>
                                    <key>{41}</key>
                                    <host>{1}</host>
                                 </value>
                              </field>
                           </fields>
                        </widget>
                     </widgets>
                  </page>
               </pages>
            </dashboard>
         </dashboards>
      </template>
   </templates>
</zabbix_export>
"""
    return " ".join(dashboard_xml.format(datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'),
                                         template,
                                         Connections.graph_name,
                                         PgLocks.graph_name,
                                         Instance.graphs_name["tuples"],
                                         PgBufferCache.graph_name,
                                         ArchiveCommand.key.format("[" + ArchiveCommand.Items[2][0] + "]"),
                                         Databases.key_autovacumm.format("[]"),
                                         BgWriter.graph_name_buffers,
                                         BgWriter.graph_name_ws,
                                         Instance.key + Instance.Items[1][1],
                                         Instance.key + Instance.Items[2][1],
                                         PgHealth.key_cache.format("[hit]"),
                                         Checkpoint.graph_name_count,
                                         Checkpoint.graph_name_ws,
                                         Instance.key + Instance.Items_pg_12[0][1],
                                         Instance.key + Instance.Items[0][1],
                                         Memory.key.format("[" + Memory.Items[5][0] + "]"),
                                         Memory.key.format("[" + Memory.Items[3][0] + "]"),
                                         ProcStat.key + ProcStat.CpuItems[4][1],
                                         Memory.key.format("[" + Memory.Items[0][0] + "]"),
                                         Instance.key + Instance.Items[4][1],
                                         Instance.graphs_name["events"],
                                         ArchiveCommand.key.format("[" + ArchiveCommand.Items[3][0] + "]"),
                                         ArchiveCommand.key.format("[" + ArchiveCommand.Items[0][0] + "]"),
                                         Replication.key_non_active_slots.format("[]"),
                                         Oldest.key.format("[transaction_time]"),
                                         PgHealth.key_ping.format("[]"),
                                         PgHealth.key_version.format("[]"),
                                         Replication.key_replication.format("[sec]"),
                                         ArchiveCommand.key.format("[" + ArchiveCommand.Items[1][0] + "]"),
                                         Instance.key + Instance.Items[6][1],
                                         Instance.key + Instance.Items[7][1],
                                         Connections.key.format("[total]"),
                                         Instance.key + Instance.Items[8][1],
                                         Instance.key + Instance.Items[9][1],
                                         Instance.key + Instance.Items[10][1],
                                         Instance.key + Instance.Items[11][1],
                                         PgHealth.key_uptime.format("[]"),
                                         Wal.key_wal_records.format("[]"),
                                         Wal.key_wal_sync_duty,
                                         Wal.key_wall.format("[]"),
                                         uuid).replace("\\r\\n", " ").split())
