
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "91062e7d4a05b76ab38b8146427a54987d6d1269",
 "version": "1.15.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
