#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_version 2.0
db_capb
db_title Configure mamonsu agent


VARS=/var/lib/mamonsu/agent.sh

_load_env() {
    [ -f $VARS ] && . $VARS
    [ ! -n "$CLIENT" ] && CLIENT=$(hostname -f || 'locahost')
    [ ! -n "$ADDRESS" ] && ADDRESS="127.0.0.1"
    [ ! -n "$USER" ] && USER="postgres"
    [ ! -n "$PASS" ] && PASS="None"
    [ ! -n "$DATABASE" ] && DATABASE="postgres"
    [ ! -n "$HOST" ] && HOST="auto"
    [ ! -n "$PORT" ] && PORT="5432"
    [ ! -n "$TIMEOUT" ] && TIMEOUT="10"
    [ ! -n "$LEVEL" ] && LEVEL="INFO"
}

_load_env

db_set mamonsu/zabbix_client "$CLIENT"
db_set mamonsu/zabbix_address "$ADDRESS"
db_set mamonsu/postgres_user "$USER"
db_set mamonsu/postgres_password "$PASS"
db_set mamonsu/postgres_database "$DATABASE"
db_set mamonsu/postgres_host "$HOST"
db_set mamonsu/postgres_port "$PORT"
db_set mamonsu/postgres_query_timeout "$TIMEOUT"
db_set mamonsu/log_level "$LEVEL"

db_input high mamonsu/zabbix_address || true
db_input high mamonsu/zabbix_client || true
db_input high mamonsu/postgres_user || true
db_input high mamonsu/postgres_password || true
db_input high mamonsu/postgres_database || true
db_input high mamonsu/postgres_host || true
db_input high mamonsu/postgres_port || true
db_input medium mamonsu/postgres_query_timeout || true
db_input medium mamonsu/log_level || true

db_go || true

