#!/bin/sh
set -e

. /usr/share/debconf/confmodule
db_version 2.0

CONFIGFILE=/etc/mamonsu/agent.conf
VARS=/var/lib/mamonsu/agent.sh

_configure_conf() {

    if [ -e $CONFIGFILE ] && [ -z "$DEBCONF_RECONFIGURE" ] ; then
        db_stop
        echo
        echo "File $CONFIGFILE exists, leaving unchanged."
        return 0
    fi

    dbc_go mamonsu

    db_get mamonsu/zabbix_address
    ADDRESS="$RET"
    db_get mamonsu/zabbix_client
    CLIENT="$RET"
    db_get mamonsu/postgres_user
    USER="$RET"
    db_get mamonsu/postgres_password
    PASSWD="$RET"
    db_get mamonsu/postgres_database
    DATABASE="$RET"
    db_get mamonsu/postgres_host
    HOST="$RET"
    db_get mamonsu/postgres_port
    PORT="$RET"
    db_get mamonsu/postgres_query_timeout
    TIMEOUT="$RET"

    echo "
[zabbix]
; zabbix server address
address = $ADDRESS
; configured 'Host name' of client in zabbix server
client = $CLIENT

[postgres]
user = $USER
database = $DATABASE
password = $PASSWD
host = $HOST
port = $PORT
query_timeout = $TIMEOUT

[plugins]
directory = /etc/mamonsu/plugins

[log]
file = /var/log/mamonsu/agent.log
level = INFO
" > $CONFIGFILE

    echo "
CLIENT='$CLIENT'
ADDRESS='$ADDRESS'
PG_USER='$USER'
PASSWD='$PASSWD'
DATABASE='$DATABASE'
HOST='$HOST'
PORT='$PORT'
TIMEOUT='$TIMEOUT'
LEVEL='$LEVEL'
" > $VARS

}


if [ "$1" = "configure" ]; then

    if ! getent group mamonsu > /dev/null 2>&1 ; then
        addgroup --system --quiet mamonsu
    fi
    if ! getent passwd mamonsu > /dev/null 2>&1 ; then
        adduser --quiet \
            --system --disabled-login --ingroup mamonsu \
            --home /var/run/mamonsu/ --no-create-home \
            mamonsu
    fi

    mkdir -p /var/run/mamonsu
    chown mamonsu:mamonsu /var/run/mamonsu

    mkdir -p /etc/mamonsu/plugins
    touch /etc/mamonsu/plugins/__init__.py

    chown mamonsu:mamonsu /var/log/mamonsu
    chown mamonsu:mamonsu /var/lib/mamonsu

    _configure_conf

fi

db_stop

if [ -x "/etc/init.d/mamonsu" ]; then
    update-rc.d mamonsu defaults >/dev/null
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d mamonsu start || exit $?
    else
        /etc/init.d/mamonsu start || exit $?
    fi
fi

exit 0
